"""create todos table

Revision ID: 003fa03cde3e
Revises: bea2e3b764b0
Create Date: 2026-05-30 20:08:15.577452

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '003fa03cde3e'
down_revision: Union[str, Sequence[str], None] = 'bea2e3b764b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'todos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column(
            'state',
            sa.Enum('draft', 'todo', 'doing', 'done', 'trash', name='todostate'),
            nullable=False,
        ),
        sa.Column('use_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['use_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
